### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by luceos** [FriendsOfFlarum/passport#1]
@clarkwinkelmann can you update the readme to match the thread?

https://discuss.flarum.org/d/5203-flagrow-passport-the-laravel-passport-oauth-extension

I normally just copy that one into the readme, but now that you created one of your own it might be best to merge information you found important to the thread and readme.

;)

**Comment by clarkwinkelmann** [comment]
I did copy text from your thread, but I changed the format to have the configuration as a table and with examples.

I did miss the update section tough. Should I also copy the Passport excerpt ?

**Comment by Luceos** [comment]
Oh, I was missing links to the Laravel docs I guess 😁 Feel free to close however you please.
