### ISSUE TITLE
Support for WordPress

### ISSUE THREAD

**Issue by allroundernaman** [FriendsOfFlarum/passport#11]
Hi There!

I want that plugin should authenticate easily using wordpress. Maybe a another FoF plugin for WordPress. 
Also block the default registration method.

**Comment by clarkwinkelmann** [comment]
Have you taken a look at the existing extensions made specially for Wordpress? One is paid (and made by me) and the other has a free version and also some paid features. You can find them by searching the Discuss forum.

The goal of this extension is simply to interface with oauth-compatible servers.

You should be able to get this extension working with Wordpress by installing an oauth-compatible server plugin on Wordpress, though I'm not sure if that's been done before and it would only provide the most basic integration compared to the dedicated Wordpress extensions.

In regard to disabling email login or registration, this is a popular demand. This would be best as its own extension, seeing this would be useful with any social login. But such an extension doesn't exist at this time. My own Wordpress paid extension does include that feature.

**Comment by allroundernaman** [comment]
Thanks for the help.
Can you provide me some links from where I can refer to?

**Comment by clarkwinkelmann** [comment]
https://discuss.flarum.org/d/21666-php-and-wordpress-single-sign-on-sso
https://discuss.flarum.org/d/22229-premium-wordpress-integration
