### ISSUE TITLE
bug error.

### ISSUE THREAD

**Issue by gfd6th** [FriendsOfFlarum/passport#2]
Laravel version: 5.5.*,
flarum: beta7
passport: ^4.0

There was an error when I login.
```
Fatal error: Uncaught TypeError: Argument 1 passed to Flagrow\Passport\Providers\PassportProvider::createResourceOwner() must be of the type array, string given, called in /Users/hexu/learning/bbs/vendor/league/oauth2-client/src/Provider/AbstractProvider.php on line 778 and defined in /Users/hexu/learning/bbs/vendor/flagrow/passport/src/Providers/PassportProvider.php on line 93
```

**Comment by clarkwinkelmann** [comment]
I can't be sure but I suspect this is because the API call for the user details does not return the correct JSON payload. Does your login server has an `/api/user` endpoint returning a json object with an `email` key ? It's usually already created in a new Laravel app

**Comment by Ralkage** [comment]
Hi @gfd6th, is this still an issue? Please refer to @clarkwinkelmann's response and reply back as soon as you can.

We will close this issue 7 days from now if no response has been given.

Thank you for your patience :)
