### ISSUE TITLE
put a link in redirect page

### ISSUE THREAD

**Issue by blankwy** [FriendsOfFlarum/passport#38]
## Feature Request

When I completing the oauth in some browser which **without supports to pop up window** etc.,the account program will redirect to the redirect_url(`<your flarum install>/auth/passport`),but the redirect_url won't redirect to the target url(such as binding or register account),the page will **stay in blank.**

It result in that if I put the flarum in a webview of app(don't support multiple windows normally),the plugin can't work.

**Some tips and a link to redirect to target page** can be put in the page of redirect_url after authorizing,user can click to redirect manually.

**Comment by clarkwinkelmann** [comment]
I actually created a separate extension that addresses this issue https://github.com/clarkwinkelmann/flarum-ext-auth-popup-failsafe
