### ISSUE TITLE
use sub instead of id

### ISSUE THREAD

**Issue by nched** [FriendsOfFlarum/passport#40]
## Feature Request
The standard in verifying user information is sub instead of id. Many oauth implementations will deliver the user id as sub.
https://www.oauth.com/oauth2-servers/signing-in-with-google/verifying-the-user-info/

It would be useful to change id to sub

**Describe the solution you'd like**
    public function getId()
    {
        return $this->getValueByKey(
            $this->response,
            Arr::get(static::$fields, 'sub', 'sub')
        );
    }

**Comment by luceos** [comment]
This extension was primarily created to work with the Laravel Passport package. If you really need it to be more flexible either sent in a PR that adds this without losing the current logic, or commission a developer to do it.

As you mention google, you might also be interested in the FriendsOfFlarum OAuth extension, it actually works with Google: https://extiverse.com/extension/fof/oauth

**Comment by nched** [comment]
thank you Luceos for the info. I was looking for a standard oauth plugin and passport is far more useable than the normal oauht extension, because it allows to set client-id, secret, scope, etc. The ouath extension is limited to the standard oauth providers - which I don't use. I guess I write a patch that I can apply via composer.

**Comment by luceos** [comment]
@imorland this can be closed
