### ISSUE TITLE
Redirect url mismatch

### ISSUE THREAD

**Issue by vlntsolo** [FriendsOfFlarum/passport#6]
Provides partial redirect value for OAuth authorization query https://example.com/oauth/authorize
https://i.imgur.com/toHXGDP.png
Flarum config.php includes full url with subdirectory:  'url' => 'https://myflarum/sub'

Nginx conf sample:

`location ~ /(?<content>[^/]+) {
        try_files $uri $uri/ /$content/index.php?$query_string;
    }
`

**Comment by clarkwinkelmann** [comment]
Could this be similar to the people who had issues with the Facebook redirects in the past ? https://discuss.flarum.org/d/19340-facebook-login-not-redirect-to-flarum-folder/16

I'm not sure if any fix was found in Flarum in the end...

**Comment by clarkwinkelmann** [comment]
Closed by #7
