### ISSUE TITLE
Required option not passed: "access_token"

### ISSUE THREAD

**Issue by Ghost-chu** [FriendsOfFlarum/passport#8]
[Whoops! There was an error.zip](https://github.com/FriendsOfFlarum/passport/files/4415788/Whoops.There.was.an.error.zip)

**Comment by Ghost-chu** [comment]
I think this is a api issue because it works after i tested github api.

**Comment by Supernova3339** [comment]
Fixed it

**Comment by luceos** [comment]
> Fixed it

Can you then please explain what fixed it, so that the next supernova3339 with the same question doesn't ask the same question without getting an answer? 😊 Thanks!

**Comment by Supernova3339** [comment]
invalid placement in config/auth.php :)
